name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: php:8.2-cli
    steps:
      - name: Hacer checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias del sistema
        run: |
          apt-get update && apt-get install -y unzip libzip-dev
          docker-php-ext-install zip

      - name: Instalar Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      - name: Instalar dependencias
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Instalar PHPUnit
        run: composer require --dev phpunit/phpunit
        
      - name: Ejecutamos test
        run: vendor/bin/phpunit --verbose --testdox || exit 1

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Hacer checkout
        uses: actions/checkout@v4

      - name: Loguearse en docker
        run: |
          echo "Logueandose..."
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: pedromm04/calculadora:latest
