name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout
        uses: actions/checkout@v4

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpunit

      - name: Instalar dependencias
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Listar archivos del proyecto
        run: ls -la

      - name: Ejecutamos test
        run: vendor/bin/phpunit --testdox

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Hacer checkout
        uses: actions/checkout@v4

      - name: Loguearse en docker
        run: |
          echo "Logueandose..."
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          target: prod
          tags: pedromm04/calculadora:latest
