name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer checkout
        uses: actions/checkout@v4

      - name: Loguearse en docker
        run: |
          echo "Logueandose..."
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Construyendo la imagen
        run: docker build -t pedromm04/calculadora:latest . 
      - name: Subiendo imagen
        run: docker push pedromm04/calculadora:latest
